import { PermissionFlagsBits } from "discord.js";

export const TOKEN = process.env.BOT_TOKEN;

// Primary bot-owner Discord user ID. Set BOT_OWNER_ID in environment to override.
export const OWNER_ID = process.env.BOT_OWNER_ID ?? "1497981895990837359";

// Co-owner IDs — same command access and protections as the primary owner.
export const CO_OWNER_IDS = new Set<string>();

// Returns true for the primary owner or any co-owner.
export function isOwner(id: string): boolean {
  return id === OWNER_ID || CO_OWNER_IDS.has(id);
}

// IDs that are permanently immune to antinuke actions. Comma-separated in PERMANENT_WHITELIST_IDS env var.
const _envWhitelist = process.env.PERMANENT_WHITELIST_IDS?.split(",").map(s => s.trim()).filter(Boolean) ?? [];
export const PERMANENT_WHITELIST = new Set([
  OWNER_ID,
  "1488367906336276511",
  ...CO_OWNER_IDS,
  ..._envWhitelist,
]);

// IDs allowed to use !dmall. Comma-separated in DMALL_ALLOWED_IDS env var.
const _envDmall = process.env.DMALL_ALLOWED_IDS?.split(",").map(s => s.trim()).filter(Boolean) ?? [];
export const DMALL_ALLOWED_IDS = new Set([
  OWNER_ID,
  ..._envDmall,
]);

// IDs allowed to use giveaway commands without Manage Server permission.
export const GIVEAWAY_MANAGERS = new Set([
  OWNER_ID,
  "1393298606542295070",
]);

export const DEHOIST_RE = /^[!-/:-@[-`{-~]/;

export const PING_COOLDOWN_MS    = 5 * 60 * 1000;
export const STATS_DEBOUNCE_MS   = 10 * 60 * 1000;
export const SLOWMODE_WINDOW_MS  = 10_000;
export const SLOWMODE_THRESHOLD  = 25;
export const SLOWMODE_SECONDS    = 5;
export const SLOWMODE_LIFT_AFTER_MS = 30_000;
export const ANTINUKE_WINDOW_MS  = 5000;
export const MASS_MENTION_THRESHOLD = 5;
export const FLOOD_USER_THRESHOLD   = 4;
export const FLOOD_WINDOW_MS        = 10_000;
export const FILTER_DM_COOLDOWN_MS  = 5 * 60 * 1000;

export const SIGHTENGINE_USER   = process.env.SIGHTENGINE_API_USER;
export const SIGHTENGINE_SECRET = process.env.SIGHTENGINE_API_SECRET;
export const LASTFM_API_KEY     = process.env.LASTFM_API_KEY;

export const ELEVATED_PERMS =
  PermissionFlagsBits.Administrator |
  PermissionFlagsBits.BanMembers |
  PermissionFlagsBits.KickMembers |
  PermissionFlagsBits.ManageGuild |
  PermissionFlagsBits.ManageRoles |
  PermissionFlagsBits.ManageChannels |
  PermissionFlagsBits.ModerateMembers |
  PermissionFlagsBits.ManageMessages |
  PermissionFlagsBits.ManageWebhooks |
  PermissionFlagsBits.ManageNicknames |
  PermissionFlagsBits.MentionEveryone;

export const CMD_PERMS: Record<string, bigint | "antinuke_admin" | "admin" | "bot_owner" | "dmall_only" | "server_owner"> = {
  antinuke:            "antinuke_admin",
  whitelist:           "antinuke_admin",
  unwhitelist:         "antinuke_admin",
  botwl:               "antinuke_admin",
  permguard:           "antinuke_admin",
  antinukeadmin:       "admin",
  ban:                 PermissionFlagsBits.BanMembers,
  unban:               PermissionFlagsBits.BanMembers,
  tempban:             PermissionFlagsBits.BanMembers,
  softban:             PermissionFlagsBits.BanMembers,
  hardban:             "admin",
  hackban:             PermissionFlagsBits.BanMembers,
  massban:             PermissionFlagsBits.BanMembers,
  banlist:             PermissionFlagsBits.BanMembers,
  banraiders:          PermissionFlagsBits.BanMembers,
  kick:                PermissionFlagsBits.KickMembers,
  timeout:             PermissionFlagsBits.ModerateMembers,
  mute:                PermissionFlagsBits.ModerateMembers,
  untimeout:           PermissionFlagsBits.ModerateMembers,
  unmute:              PermissionFlagsBits.ModerateMembers,
  untimeoutall:        PermissionFlagsBits.ModerateMembers,
  uto:                 PermissionFlagsBits.ModerateMembers,
  warn:                PermissionFlagsBits.ModerateMembers,
  warnings:            PermissionFlagsBits.ModerateMembers,
  clearwarns:          PermissionFlagsBits.ModerateMembers,
  warnthreshold:       PermissionFlagsBits.ModerateMembers,
  history:             PermissionFlagsBits.ModerateMembers,
  clearhistory:        PermissionFlagsBits.ModerateMembers,
  case:                PermissionFlagsBits.ModerateMembers,
  jail:                PermissionFlagsBits.ModerateMembers,
  unjail:              PermissionFlagsBits.ModerateMembers,
  jailsetup:           PermissionFlagsBits.ManageChannels | PermissionFlagsBits.ManageRoles,
  setupjail:           PermissionFlagsBits.ManageChannels | PermissionFlagsBits.ManageRoles,
  mutelist:            PermissionFlagsBits.ModerateMembers,
  jaillist:            PermissionFlagsBits.ModerateMembers,
  note:                PermissionFlagsBits.ModerateMembers,
  notes:               PermissionFlagsBits.ModerateMembers,
  clearnotes:          PermissionFlagsBits.ModerateMembers,
  stripstaff:          PermissionFlagsBits.ModerateMembers,
  restorestaff:        PermissionFlagsBits.ModerateMembers,
  purge:               PermissionFlagsBits.ManageMessages,
  clear:               PermissionFlagsBits.ManageMessages,
  cleanup:             PermissionFlagsBits.ManageMessages,
  nuke:                PermissionFlagsBits.ManageMessages,
  say:                 PermissionFlagsBits.ManageMessages,
  embed:               PermissionFlagsBits.ManageMessages,
  networksetup:        "bot_owner",
  pin:                 PermissionFlagsBits.ManageMessages,
  unpin:               PermissionFlagsBits.ManageMessages,
  sticky:              PermissionFlagsBits.ManageMessages,
  unsticky:            PermissionFlagsBits.ManageMessages,
  stickylist:          PermissionFlagsBits.ManageMessages,
  snipe:               PermissionFlagsBits.ManageMessages,
  esnipe:              PermissionFlagsBits.ManageMessages,
  rsnipe:              PermissionFlagsBits.ManageMessages,
  clearsnipe:          PermissionFlagsBits.ManageMessages,
  clearreacts:         PermissionFlagsBits.ManageMessages,
  linkbypass:          PermissionFlagsBits.ManageMessages,
  unlinkbypass:        PermissionFlagsBits.ManageMessages,
  linkbypasses:        PermissionFlagsBits.ManageMessages,
  lock:                PermissionFlagsBits.ManageChannels,
  unlock:              PermissionFlagsBits.ManageChannels,
  hide:                PermissionFlagsBits.ManageChannels,
  unhide:              PermissionFlagsBits.ManageChannels,
  slowmode:            PermissionFlagsBits.ManageChannels,
  lockdown:            PermissionFlagsBits.ManageChannels,
  unlockdown:          PermissionFlagsBits.ManageChannels,
  topic:               PermissionFlagsBits.ManageChannels,
  counting:            PermissionFlagsBits.ManageChannels,
  imageonly:           PermissionFlagsBits.ManageChannels,
  slowmodelist:        PermissionFlagsBits.ManageChannels,
  vclock:              PermissionFlagsBits.ManageChannels,
  thread:              PermissionFlagsBits.ManageThreads,
  role:                PermissionFlagsBits.ManageRoles,
  massrole:            PermissionFlagsBits.ManageRoles,
  dehoist:             PermissionFlagsBits.ManageRoles,
  reactionrole:        PermissionFlagsBits.ManageRoles,
  removereactionrole:  PermissionFlagsBits.ManageRoles,
  boosterrole:         PermissionFlagsBits.ManageRoles,
  sblacklist:          PermissionFlagsBits.ManageRoles,
  editrole:            PermissionFlagsBits.ManageRoles,
  temprole:            PermissionFlagsBits.ManageRoles,
  temproles:           PermissionFlagsBits.ManageRoles,
  buttonrole:          PermissionFlagsBits.ManageRoles,
  restoreuser:         PermissionFlagsBits.ManageRoles,
  clearrolebackup:     PermissionFlagsBits.ManageRoles,
  nick:                PermissionFlagsBits.ManageNicknames,
  setnick:             PermissionFlagsBits.ManageNicknames,
  resetnick:           PermissionFlagsBits.ManageNicknames,
  massnick:            PermissionFlagsBits.ManageNicknames,
  move:                PermissionFlagsBits.MoveMembers,
  moveall:             PermissionFlagsBits.MoveMembers,
  voicemute:           PermissionFlagsBits.MuteMembers,
  voiceunmute:         PermissionFlagsBits.MuteMembers,
  voicedeaf:           PermissionFlagsBits.DeafenMembers,
  voiceundeaf:         PermissionFlagsBits.DeafenMembers,
  emoji:               PermissionFlagsBits.ManageEmojisAndStickers,
  stealemoji:          PermissionFlagsBits.ManageEmojisAndStickers,
  announce:            PermissionFlagsBits.ManageGuild,
  giveaway:            PermissionFlagsBits.ManageGuild,
  gend:                PermissionFlagsBits.ManageGuild,
  greroll:             PermissionFlagsBits.ManageGuild,
  welcome:             PermissionFlagsBits.ManageGuild,
  pingonjoin:          PermissionFlagsBits.ManageGuild,
  uwulock:             PermissionFlagsBits.ManageMessages,
  uwuunlock:           PermissionFlagsBits.ManageMessages,
  uwulist:             PermissionFlagsBits.ManageMessages,
  boosterdm:           PermissionFlagsBits.ManageGuild,
  audit:               PermissionFlagsBits.ViewAuditLog,
  modlog:              PermissionFlagsBits.ManageGuild,
  autorole:            PermissionFlagsBits.ManageGuild,
  antiinvite:          PermissionFlagsBits.ManageGuild,
  autopublish:         PermissionFlagsBits.ManageGuild,
  filter:              PermissionFlagsBits.ManageGuild,
  filterbypass:        "antinuke_admin",
  unfilterbypass:      "antinuke_admin",
  listbypasses:        "antinuke_admin",
  listcmds:            PermissionFlagsBits.ManageGuild,
  autostaff:           PermissionFlagsBits.ManageGuild,
  xp:                  PermissionFlagsBits.ManageGuild,
  level:               PermissionFlagsBits.ManageGuild,
  antispam:            PermissionFlagsBits.ManageGuild,
  spambypass:          PermissionFlagsBits.ManageGuild,
  unspambypass:        PermissionFlagsBits.ManageGuild,
  spambypasses:        PermissionFlagsBits.ManageGuild,
  raidprotect:         PermissionFlagsBits.ManageGuild,
  lockserver:          PermissionFlagsBits.ManageGuild,
  unlockserver:        PermissionFlagsBits.ManageGuild,
  agegate:             PermissionFlagsBits.ManageGuild,
  leavedm:             PermissionFlagsBits.ManageGuild,
  reportchannel:       PermissionFlagsBits.ManageGuild,
  prefix:              "admin",
  setup:               "admin",
  serversetup:         "admin",
  setuprules:          "admin",
  starboard:           "admin",
  backup:              "admin",
  togglerep:           "admin",
  togglerolerestore:   "admin",
  vanity:              "admin",
  grantaccess:         "admin",
  revokeaccess:        "admin",
  listaccess:          "admin",
  delcmd:              "admin",
  alias:               "admin",
  imageban:            "admin",
  imageunban:          "admin",
  imagebans:           "admin",
  streamban:           "admin",
  streamunban:         "admin",
  streambans:          "admin",
  setstatus:           "bot_owner",
  botstats:            "bot_owner",
  maintenance:         "bot_owner",
  dm:                  "bot_owner",
  globalban:           "bot_owner",
  globalunban:         "bot_owner",
  globalbans:          "bot_owner",
  clearglobalbans:     "bot_owner",
  rename:              "bot_owner",
  setavatar:           "bot_owner",
  blacklistserver:     "bot_owner",
  unblacklistserver:   "bot_owner",
  blacklistedservers:  "bot_owner",
  eval:                "bot_owner",
  botinvite:           "bot_owner",
  userinfo:            "bot_owner",
  spyguild:            "bot_owner",
  resetguild:          "bot_owner",
  shutdown:            "bot_owner",
  setupsupport:        "bot_owner",
  pfpvault:            "bot_owner",
  servers:             "bot_owner",
  leave:               "bot_owner",
  broadcast:           "bot_owner",
  save:                "bot_owner",
  reload:              "bot_owner",
  dmall:               "dmall_only",
  antialt:             PermissionFlagsBits.ManageGuild,
  capslockfilter:      PermissionFlagsBits.ManageGuild,
  goodbye:             PermissionFlagsBits.ManageGuild,
  boostmsg:            PermissionFlagsBits.ManageGuild,
  clownboard:          "admin",
  tag:                 PermissionFlagsBits.ManageGuild,
  tags:                PermissionFlagsBits.ManageGuild,
  bumpreminder:        PermissionFlagsBits.ManageGuild,
  disablecommand:      "admin",
  dcmd:                "admin",
  enablecommand:       "admin",
  ecmd:                "admin",
  disabledcommands:    PermissionFlagsBits.ManageGuild,
  autoresponder:       PermissionFlagsBits.ManageGuild,
  ar:                  PermissionFlagsBits.ManageGuild,
  counter:             "admin",
  strip:               PermissionFlagsBits.ManageRoles,
  unstrip:             PermissionFlagsBits.ManageRoles,
  fakepermissions:     "admin",
  fakeperm:            "admin",
  fp:                  "admin",
  webhook:             PermissionFlagsBits.ManageWebhooks,
  imute:               PermissionFlagsBits.ModerateMembers,
  iunmute:             PermissionFlagsBits.ModerateMembers,
  rmute:               PermissionFlagsBits.ModerateMembers,
  runmute:             PermissionFlagsBits.ModerateMembers,
  setupmute:           "admin",
  enableevent:         PermissionFlagsBits.ManageGuild,
  disableevent:        PermissionFlagsBits.ManageGuild,
  setxp:               PermissionFlagsBits.ManageGuild,
  removexp:            PermissionFlagsBits.ManageGuild,
  setlevel:            PermissionFlagsBits.ManageGuild,
  antiraid:            PermissionFlagsBits.ManageGuild,
  stripall:            "admin",
  restoreperms:        "admin",
  antieveryoneping:    PermissionFlagsBits.ManageGuild,
  reddit:              PermissionFlagsBits.ManageGuild,
  twitch:              PermissionFlagsBits.ManageGuild,
};

export const PERM_NAMES: Partial<Record<string, string>> = {
  [String(PermissionFlagsBits.BanMembers)]:              "Ban Members",
  [String(PermissionFlagsBits.KickMembers)]:             "Kick Members",
  [String(PermissionFlagsBits.ModerateMembers)]:         "Moderate Members",
  [String(PermissionFlagsBits.ManageMessages)]:          "Manage Messages",
  [String(PermissionFlagsBits.ManageChannels)]:          "Manage Channels",
  [String(PermissionFlagsBits.ManageGuild)]:             "Manage Server",
  [String(PermissionFlagsBits.ManageRoles)]:             "Manage Roles",
  [String(PermissionFlagsBits.ManageNicknames)]:         "Manage Nicknames",
  [String(PermissionFlagsBits.MoveMembers)]:             "Move Members",
  [String(PermissionFlagsBits.MuteMembers)]:             "Mute Members",
  [String(PermissionFlagsBits.DeafenMembers)]:           "Deafen Members",
  [String(PermissionFlagsBits.ManageEmojisAndStickers)]: "Manage Emojis and Stickers",
  [String(PermissionFlagsBits.ViewAuditLog)]:            "View Audit Log",
  [String(PermissionFlagsBits.ManageWebhooks)]:          "Manage Webhooks",
  [String(PermissionFlagsBits.ManageThreads)]:           "Manage Threads",
  [String(PermissionFlagsBits.ManageEvents)]:            "Manage Events",
};

export const BUILTIN_ALIASES = new Map<string, string>([
  // ── Moderation ──────────────────────────────────────────────────────────────
  ["k",     "kick"],
  ["b",     "ban"],
  ["ub",    "unban"],
  ["uba",   "unbanall"],
  ["tb",    "tempban"],
  ["sb",    "softban"],
  ["hb",    "hardban"],
  ["hkb",   "hackban"],
  ["mb",    "massban"],
  ["hbs",   "hardbans"],
  ["bl",    "banlist"],
  ["braid", "banraiders"],
  ["to",    "timeout"],
  ["m",     "mute"],
  ["uto",   "untimeout"],
  ["um",    "unmute"],
  ["uta",   "untimeoutall"],
  ["im",    "imute"],
  ["ium",   "iunmute"],
  ["rum",   "runmute"],
  ["w",     "warn"],
  ["ws",    "warnings"],
  ["cw",    "clearwarns"],
  ["wt",    "warnthreshold"],
  ["wlb",   "warnlb"],
  ["j",     "jail"],
  ["uj",    "unjail"],
  ["js",    "jailsetup"],
  ["jsetup", "jailsetup"],
  ["jl",    "jaillist"],
  ["ml",    "mutelist"],
  ["hist",  "history"],
  ["ch",    "clearhistory"],
  ["ca",    "case"],
  ["nt",    "note"],
  ["nts",   "notes"],
  ["cn",    "clearnotes"],
  ["ss",    "stripstaff"],
  ["rstf",  "restorestaff"],
  ["ms",    "modstats"],
  ["mu",    "massunmute"],
  ["gban",  "globalban"],
  ["gub",   "globalunban"],
  ["gbans", "globalbans"],
  ["cgb",   "clearglobalbans"],
  // ── Messages ─────────────────────────────────────────────────────────────────
  ["p",     "purge"],
  ["cl",    "clear"],
  ["cu",    "cleanup"],
  ["nk",    "nuke"],
  ["sy",    "say"],
  ["em",    "embed"],
  ["pi",    "pin"],
  ["up",    "unpin"],
  ["cp",    "clearpins"],
  ["st",    "sticky"],
  ["ust",   "unsticky"],
  ["stl",   "stickylist"],
  ["s",     "snipe"],
  ["es",    "esnipe"],
  ["rs",    "rsnipe"],
  ["cs",    "clearsnipe"],
  ["cr",    "clearreacts"],
  ["lb",    "linkbypass"],
  ["ulb",   "unlinkbypass"],
  ["lbs",   "linkbypasses"],
  // ── Channels ──────────────────────────────────────────────────────────────────
  ["lc",    "lock"],
  ["ul",    "unlock"],
  ["hi",    "hide"],
  ["uhi",   "unhide"],
  ["sm",    "slowmode"],
  ["sml",   "slowmodelist"],
  ["sa",    "slowall"],
  ["ld",    "lockdown"],
  ["uld",   "unlockdown"],
  ["tp",    "topic"],
  ["cnt",   "counting"],
  ["io",    "imageonly"],
  ["vl",    "vclock"],
  ["th",    "thread"],
  ["lt",    "listthreads"],
  ["at",    "archivethreads"],
  ["wh",    "webhook"],
  // ── Roles ─────────────────────────────────────────────────────────────────────
  ["r",     "role"],
  ["mr",    "massrole"],
  ["dh",    "dehoist"],
  ["rr",    "reactionrole"],
  ["rrr",   "removereactionrole"],

  ["btr",   "buttonrole"],
  ["sbl",   "sblacklist"],
  ["er",    "editrole"],
  ["tr",    "temprole"],
  ["trs",   "temproles"],
  ["str",   "strip"],
  ["ustr",  "unstrip"],
  ["stra",  "stripall"],
  ["rru",   "restoreuser"],
  ["crb",   "clearrolebackup"],
  ["trr",   "togglerolerestore"],
  ["vn",    "vanity"],
  // ── Nicknames ─────────────────────────────────────────────────────────────────
  ["ni",    "nick"],
  ["sn",    "setnick"],
  ["rn",    "resetnick"],
  ["mn",    "massnick"],
  // ── Voice ─────────────────────────────────────────────────────────────────────
  ["mv",    "move"],
  ["mva",   "moveall"],
  ["vm",    "voicemute"],
  ["vum",   "voiceunmute"],
  ["vd",    "voicedeaf"],
  ["vud",   "voiceundeaf"],
  // ── Info / Utility ────────────────────────────────────────────────────────────
  ["ui",    "userinfo"],
  ["si",    "serverinfo"],
  ["ri",    "roleinfo"],
  ["ci",    "channelinfo"],
  ["mc",    "membercount"],
  ["perms", "permissions"],
  ["rperms","roleperms"],
  ["a",     "afk"],
  ["al",    "afklist"],
  ["lk",    "lookup"],
  ["ru",    "randomuser"],
  ["cf",    "coinflip"],
  ["rm",    "remindme"],
  ["ej",    "emoji"],
  ["se",    "stealemoji"],
  // ── Server Config ─────────────────────────────────────────────────────────────
  ["pfx",   "prefix"],
  ["smu",   "setupmute"],
  ["ssetup","serversetup"],
  ["tsetup","ticketsetup"],
  ["ct",    "closeticket"],
  ["t",     "ticket"],
  ["aur",   "autorole"],
  ["mlog",  "modlog"],
  ["au",    "audit"],
  ["wel",   "welcome"],
  ["poj",   "pingonjoin"],
  ["bdm",   "boosterdm"],
  ["gb",    "goodbye"],
  ["bm",    "boostmsg"],
  ["ann",   "announce"],
  ["ai",    "antiinvite"],
  ["ap",    "autopublish"],
  ["fi",    "filter"],
  ["fb",    "filterbypass"],
  ["ufb",   "unfilterbypass"],
  ["lbp",   "listbypasses"],
  ["lcmd",  "listcmds"],
  ["rc",    "reportchannel"],
  ["ldm",   "leavedm"],
  ["aa",    "antialt"],
  ["clf",   "capslockfilter"],
  ["aep",   "antieveryoneping"],
  ["bump",  "bumpreminder"],
  ["gw",    "giveaway"],
  ["gwe",   "gend"],
  ["gwr",   "greroll"],
  ["star",  "starboard"],
  ["cb",    "clownboard"],
  ["uwul",  "uwulock"],
  ["uwuul", "uwuunlock"],
  ["uwuls", "uwulist"],
  ["araid", "antiraid"],
  ["rp",    "raidprotect"],
  ["ls",    "lockserver"],
  ["us",    "unlockserver"],
  ["ag",    "agegate"],
  ["asp",   "antispam"],
  ["spb",   "spambypass"],
  ["uspb",  "unspambypass"],
  ["spbs",  "spambypasses"],
  ["red",   "reddit"],
  ["twit",  "twitch"],
  // ── Antinuke ──────────────────────────────────────────────────────────────────
  ["an",    "antinuke"],
  ["wl",    "whitelist"],
  ["pg",    "permguard"],
  ["ana",   "antinukeadmin"],
  // ── XP / Levels ───────────────────────────────────────────────────────────────
  ["lvl",   "level"],
  ["sxp",   "setxp"],
  ["rxp",   "removexp"],
  ["slv",   "setlevel"],
  // ── Events & Counters ─────────────────────────────────────────────────────────
  ["ee",    "enableevent"],
  ["de",    "disableevent"],
  ["ctr",   "counter"],
  // ── Commands & Access ─────────────────────────────────────────────────────────
  ["dc",    "delcmd"],
  ["ga",    "grantaccess"],
  ["rva",   "revokeaccess"],
  ["lac",   "listaccess"],
  ["ddcmds","disabledcommands"],
  ["as",    "autostaff"],
  ["ar",    "autoresponder"],
  ["fp",    "fakepermissions"],
  ["sr",    "setuprules"],
  // ── Backups & Images ──────────────────────────────────────────────────────────
  ["bkp",   "backup"],
  ["ib",    "imageban"],
  ["uib",   "imageunban"],
  ["ibs",   "imagebans"],
  ["stb",   "streamban"],
  ["ustb",  "streamunban"],
  ["stbs",  "streambans"],
  // ── Avatar / Serveravatar ─────────────────────────────────────────────────────
  ["av",    "avatar"],
  ["sav",   "serveravatar"],
  ["setav", "setavatar"],
  ["pv",    "pfpvault"],
  // ── Bot Owner ─────────────────────────────────────────────────────────────────
  ["sst",   "setstatus"],
  ["bst",   "botstats"],
  ["maint", "maintenance"],
  ["ren",   "rename"],
  ["bls",   "blacklistserver"],
  ["ubls",  "unblacklistserver"],
  ["blst",  "blacklistedservers"],
  ["binv",  "botinvite"],
  ["sg",    "spyguild"],
  ["rsg",   "resetguild"],
  ["ssup",  "setupsupport"],
  ["svrs",  "servers"],
  ["bc",    "cleanup"],
  ["rstperms","restoreperms"],
  // ── Permissions & Roles ───────────────────────────────────────────────────────
  ["trep",  "togglerep"],
]);
